module Evergreen.Migrate.V17 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Array
import Evergreen.V12.DebugParser.ElmValue
import Evergreen.V12.Types
import Evergreen.V17.DebugParser.ElmValue
import Evergreen.V17.Types
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V12.Types.FrontendModel -> ModelMigration Evergreen.V17.Types.FrontendModel Evergreen.V17.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V12.Types.BackendModel -> ModelMigration Evergreen.V17.Types.BackendModel Evergreen.V17.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V12.Types.FrontendMsg -> MsgMigration Evergreen.V17.Types.FrontendMsg Evergreen.V17.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V12.Types.ToBackend -> MsgMigration Evergreen.V17.Types.ToBackend Evergreen.V17.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V12.Types.BackendMsg -> MsgMigration Evergreen.V17.Types.BackendMsg Evergreen.V17.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V12.Types.ToFrontend -> MsgMigration Evergreen.V17.Types.ToFrontend Evergreen.V17.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_DebugParser_ElmValue_ElmValue : Evergreen.V12.DebugParser.ElmValue.ElmValue -> Evergreen.V17.DebugParser.ElmValue.ElmValue
migrate_DebugParser_ElmValue_ElmValue old =
    case old of
        Evergreen.V12.DebugParser.ElmValue.Plain p0 ->
            Evergreen.V17.DebugParser.ElmValue.Plain (p0 |> migrate_DebugParser_ElmValue_PlainValue)

        Evergreen.V12.DebugParser.ElmValue.Expandable p0 ->
            Evergreen.V17.DebugParser.ElmValue.Expandable (p0 |> migrate_DebugParser_ElmValue_ExpandableValue)


migrate_DebugParser_ElmValue_ExpandableValue : Evergreen.V12.DebugParser.ElmValue.ExpandableValue -> Evergreen.V17.DebugParser.ElmValue.ExpandableValue
migrate_DebugParser_ElmValue_ExpandableValue old =
    case old of
        Evergreen.V12.DebugParser.ElmValue.ElmSequence p0 p1 ->
            Evergreen.V17.DebugParser.ElmValue.ElmSequence (p0 |> migrate_DebugParser_ElmValue_SequenceType)
                (p1 |> List.map migrate_DebugParser_ElmValue_ElmValue)

        Evergreen.V12.DebugParser.ElmValue.ElmType p0 p1 ->
            Evergreen.V17.DebugParser.ElmValue.ElmType p0
                (p1 |> List.map migrate_DebugParser_ElmValue_ElmValue)

        Evergreen.V12.DebugParser.ElmValue.ElmRecord p0 ->
            Evergreen.V17.DebugParser.ElmValue.ElmRecord (p0 |> List.map (Tuple.mapSecond migrate_DebugParser_ElmValue_ElmValue))

        Evergreen.V12.DebugParser.ElmValue.ElmDict p0 ->
            Evergreen.V17.DebugParser.ElmValue.ElmDict (p0 |> List.map (Tuple.mapBoth migrate_DebugParser_ElmValue_ElmValue migrate_DebugParser_ElmValue_ElmValue))


migrate_DebugParser_ElmValue_PlainValue : Evergreen.V12.DebugParser.ElmValue.PlainValue -> Evergreen.V17.DebugParser.ElmValue.PlainValue
migrate_DebugParser_ElmValue_PlainValue old =
    case old of
        Evergreen.V12.DebugParser.ElmValue.ElmString p0 ->
            Evergreen.V17.DebugParser.ElmValue.ElmString p0

        Evergreen.V12.DebugParser.ElmValue.ElmChar p0 ->
            Evergreen.V17.DebugParser.ElmValue.ElmChar p0

        Evergreen.V12.DebugParser.ElmValue.ElmNumber p0 ->
            Evergreen.V17.DebugParser.ElmValue.ElmNumber p0

        Evergreen.V12.DebugParser.ElmValue.ElmBool p0 ->
            Evergreen.V17.DebugParser.ElmValue.ElmBool p0

        Evergreen.V12.DebugParser.ElmValue.ElmFunction ->
            Evergreen.V17.DebugParser.ElmValue.ElmFunction

        Evergreen.V12.DebugParser.ElmValue.ElmInternals ->
            Evergreen.V17.DebugParser.ElmValue.ElmInternals

        Evergreen.V12.DebugParser.ElmValue.ElmUnit ->
            Evergreen.V17.DebugParser.ElmValue.ElmUnit

        Evergreen.V12.DebugParser.ElmValue.ElmFile p0 ->
            Evergreen.V17.DebugParser.ElmValue.ElmFile p0

        Evergreen.V12.DebugParser.ElmValue.ElmBytes p0 ->
            Evergreen.V17.DebugParser.ElmValue.ElmBytes p0


migrate_DebugParser_ElmValue_SequenceType : Evergreen.V12.DebugParser.ElmValue.SequenceType -> Evergreen.V17.DebugParser.ElmValue.SequenceType
migrate_DebugParser_ElmValue_SequenceType old =
    case old of
        Evergreen.V12.DebugParser.ElmValue.SeqSet ->
            Evergreen.V17.DebugParser.ElmValue.SeqSet

        Evergreen.V12.DebugParser.ElmValue.SeqList ->
            Evergreen.V17.DebugParser.ElmValue.SeqList

        Evergreen.V12.DebugParser.ElmValue.SeqArray ->
            Evergreen.V17.DebugParser.ElmValue.SeqArray

        Evergreen.V12.DebugParser.ElmValue.SeqTuple ->
            Evergreen.V17.DebugParser.ElmValue.SeqTuple


migrate_Types_BackendMsgEvent_ : Evergreen.V12.Types.BackendMsgEvent_ -> Evergreen.V17.Types.BackendMsgEvent_
migrate_Types_BackendMsgEvent_ old =
    { msg = old.msg |> migrate_DebugParser_ElmValue_ElmValue
    , newModel = old.newModel |> migrate_DebugParser_ElmValue_ElmValue
    }


migrate_Types_Event : Evergreen.V12.Types.Event -> Evergreen.V17.Types.Event
migrate_Types_Event old =
    case old of
        Evergreen.V12.Types.BackendMsgEvent p0 ->
            Evergreen.V17.Types.BackendMsgEvent (p0 |> migrate_Types_BackendMsgEvent_)

        Evergreen.V12.Types.ToBackendEvent p0 ->
            Evergreen.V17.Types.ToBackendEvent (p0 |> migrate_Types_ToBackendEvent_)


migrate_Types_LoadingData : Evergreen.V12.Types.LoadingData -> Evergreen.V17.Types.LoadingData
migrate_Types_LoadingData old =
    { key = old.key
    , sessionName = old.sessionName |> migrate_Types_SessionName
    }


migrate_Types_SessionName : Evergreen.V12.Types.SessionName -> Evergreen.V17.Types.SessionName
migrate_Types_SessionName old =
    case old of
        Evergreen.V12.Types.SessionName p0 ->
            Evergreen.V17.Types.SessionName p0


migrate_Types_ToBackendEvent_ : Evergreen.V12.Types.ToBackendEvent_ -> Evergreen.V17.Types.ToBackendEvent_
migrate_Types_ToBackendEvent_ old =
    { msg = old.msg |> migrate_DebugParser_ElmValue_ElmValue
    , newModel = old.newModel |> migrate_DebugParser_ElmValue_ElmValue
    , sessionId = old.sessionId
    , clientId = old.clientId
    }
