module Evergreen.Migrate.V29 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V21.DebugParser.ElmValue
import Evergreen.V21.Types
import Evergreen.V29.DebugParser.ElmValue
import Evergreen.V29.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V21.Types.FrontendModel -> ModelMigration Evergreen.V29.Types.FrontendModel Evergreen.V29.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V21.Types.BackendModel -> ModelMigration Evergreen.V29.Types.BackendModel Evergreen.V29.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V21.Types.FrontendMsg -> MsgMigration Evergreen.V29.Types.FrontendMsg Evergreen.V29.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V21.Types.ToBackend -> MsgMigration Evergreen.V29.Types.ToBackend Evergreen.V29.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V21.Types.BackendMsg -> MsgMigration Evergreen.V29.Types.BackendMsg Evergreen.V29.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V21.Types.ToFrontend -> MsgMigration Evergreen.V29.Types.ToFrontend Evergreen.V29.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_DebugParser_ElmValue_ElmValue : Evergreen.V21.DebugParser.ElmValue.ElmValue -> Evergreen.V29.DebugParser.ElmValue.ElmValue
migrate_DebugParser_ElmValue_ElmValue old =
    case old of
        Evergreen.V21.DebugParser.ElmValue.Plain p0 ->
            Evergreen.V29.DebugParser.ElmValue.Plain (p0 |> migrate_DebugParser_ElmValue_PlainValue)

        Evergreen.V21.DebugParser.ElmValue.Expandable p0 ->
            Evergreen.V29.DebugParser.ElmValue.Expandable (p0 |> migrate_DebugParser_ElmValue_ExpandableValue)


migrate_DebugParser_ElmValue_ExpandableValue : Evergreen.V21.DebugParser.ElmValue.ExpandableValue -> Evergreen.V29.DebugParser.ElmValue.ExpandableValue
migrate_DebugParser_ElmValue_ExpandableValue old =
    case old of
        Evergreen.V21.DebugParser.ElmValue.ElmSequence p0 p1 ->
            Evergreen.V29.DebugParser.ElmValue.ElmSequence (p0 |> migrate_DebugParser_ElmValue_SequenceType)
                (p1 |> List.map migrate_DebugParser_ElmValue_ElmValue)

        Evergreen.V21.DebugParser.ElmValue.ElmType p0 p1 ->
            Evergreen.V29.DebugParser.ElmValue.ElmType p0
                (p1 |> List.map migrate_DebugParser_ElmValue_ElmValue)

        Evergreen.V21.DebugParser.ElmValue.ElmRecord p0 ->
            Evergreen.V29.DebugParser.ElmValue.ElmRecord (p0 |> List.map (Tuple.mapSecond migrate_DebugParser_ElmValue_ElmValue))

        Evergreen.V21.DebugParser.ElmValue.ElmDict p0 ->
            Evergreen.V29.DebugParser.ElmValue.ElmDict (p0 |> List.map (Tuple.mapBoth migrate_DebugParser_ElmValue_ElmValue migrate_DebugParser_ElmValue_ElmValue))


migrate_DebugParser_ElmValue_PlainValue : Evergreen.V21.DebugParser.ElmValue.PlainValue -> Evergreen.V29.DebugParser.ElmValue.PlainValue
migrate_DebugParser_ElmValue_PlainValue old =
    case old of
        Evergreen.V21.DebugParser.ElmValue.ElmString p0 ->
            Evergreen.V29.DebugParser.ElmValue.ElmString p0

        Evergreen.V21.DebugParser.ElmValue.ElmChar p0 ->
            Evergreen.V29.DebugParser.ElmValue.ElmChar p0

        Evergreen.V21.DebugParser.ElmValue.ElmNumber p0 ->
            Evergreen.V29.DebugParser.ElmValue.ElmNumber p0

        Evergreen.V21.DebugParser.ElmValue.ElmBool p0 ->
            Evergreen.V29.DebugParser.ElmValue.ElmBool p0

        Evergreen.V21.DebugParser.ElmValue.ElmFunction ->
            Evergreen.V29.DebugParser.ElmValue.ElmFunction

        Evergreen.V21.DebugParser.ElmValue.ElmInternals ->
            Evergreen.V29.DebugParser.ElmValue.ElmInternals

        Evergreen.V21.DebugParser.ElmValue.ElmUnit ->
            Evergreen.V29.DebugParser.ElmValue.ElmUnit

        Evergreen.V21.DebugParser.ElmValue.ElmFile p0 ->
            Evergreen.V29.DebugParser.ElmValue.ElmFile p0

        Evergreen.V21.DebugParser.ElmValue.ElmBytes p0 ->
            Evergreen.V29.DebugParser.ElmValue.ElmBytes p0


migrate_DebugParser_ElmValue_SequenceType : Evergreen.V21.DebugParser.ElmValue.SequenceType -> Evergreen.V29.DebugParser.ElmValue.SequenceType
migrate_DebugParser_ElmValue_SequenceType old =
    case old of
        Evergreen.V21.DebugParser.ElmValue.SeqSet ->
            Evergreen.V29.DebugParser.ElmValue.SeqSet

        Evergreen.V21.DebugParser.ElmValue.SeqList ->
            Evergreen.V29.DebugParser.ElmValue.SeqList

        Evergreen.V21.DebugParser.ElmValue.SeqArray ->
            Evergreen.V29.DebugParser.ElmValue.SeqArray

        Evergreen.V21.DebugParser.ElmValue.SeqTuple ->
            Evergreen.V29.DebugParser.ElmValue.SeqTuple


migrate_Types_FrontendMsg : Evergreen.V21.Types.FrontendMsg -> Evergreen.V29.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V21.Types.UrlClicked p0 ->
            Evergreen.V29.Types.UrlClicked p0

        Evergreen.V21.Types.UrlChanged p0 ->
            Evergreen.V29.Types.UrlChanged p0

        Evergreen.V21.Types.PressedEvent p0 ->
            Evergreen.V29.Types.PressedEvent p0

        Evergreen.V21.Types.PressedResetSession ->
            Evergreen.V29.Types.PressedResetSession

        Evergreen.V21.Types.GotRandomSessionName p0 ->
            Evergreen.V29.Types.GotRandomSessionName (p0 |> migrate_Types_SessionName)

        Evergreen.V21.Types.TypedVariantFilter p0 ->
            Evergreen.V29.Types.TypedVariantFilter p0

        Evergreen.V21.Types.PressedCollapseField p0 ->
            Evergreen.V29.Types.PressedCollapseField (p0 |> List.map migrate_Types_PathNode)

        Evergreen.V21.Types.PressedExpandField p0 ->
            Evergreen.V29.Types.PressedExpandField (p0 |> List.map migrate_Types_PathNode)

        Evergreen.V21.Types.DebounceFinished p0 ->
            Evergreen.V29.Types.DebounceFinished p0


migrate_Types_PathNode : Evergreen.V21.Types.PathNode -> Evergreen.V29.Types.PathNode
migrate_Types_PathNode old =
    case old of
        Evergreen.V21.Types.FieldNode p0 ->
            Evergreen.V29.Types.FieldNode p0

        Evergreen.V21.Types.VariantNode p0 ->
            Evergreen.V29.Types.VariantNode p0

        Evergreen.V21.Types.SequenceNode p0 ->
            Evergreen.V29.Types.SequenceNode p0

        Evergreen.V21.Types.DictNode p0 ->
            Evergreen.V29.Types.DictNode (p0 |> migrate_DebugParser_ElmValue_ElmValue)


migrate_Types_SessionName : Evergreen.V21.Types.SessionName -> Evergreen.V29.Types.SessionName
migrate_Types_SessionName old =
    case old of
        Evergreen.V21.Types.SessionName p0 ->
            Evergreen.V29.Types.SessionName p0
