module Evergreen.Migrate.V36 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Array
import AssocList
import AssocSet
import Evergreen.V31.DebugParser.ElmValue
import Evergreen.V31.Types
import Evergreen.V36.DebugParser.ElmValue
import Evergreen.V36.Types
import Lamdera.Migrations exposing (..)
import Maybe
import Time


frontendModel : Evergreen.V31.Types.FrontendModel -> ModelMigration Evergreen.V36.Types.FrontendModel Evergreen.V36.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V31.Types.BackendModel -> ModelMigration Evergreen.V36.Types.BackendModel Evergreen.V36.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V31.Types.FrontendMsg -> MsgMigration Evergreen.V36.Types.FrontendMsg Evergreen.V36.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V31.Types.ToBackend -> MsgMigration Evergreen.V36.Types.ToBackend Evergreen.V36.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V31.Types.BackendMsg -> MsgMigration Evergreen.V36.Types.BackendMsg Evergreen.V36.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V31.Types.ToFrontend -> MsgMigration Evergreen.V36.Types.ToFrontend Evergreen.V36.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V31.Types.BackendModel -> Evergreen.V36.Types.BackendModel
migrate_Types_BackendModel old =
    { sessions = old.sessions |> migrate_AssocList_Dict migrate_Types_SessionName migrate_Types_DebugSession
    }


migrate_AssocList_Dict : (a_old -> a_new) -> (b_old -> b_new) -> AssocList.Dict a_old b_old -> AssocList.Dict a_new b_new
migrate_AssocList_Dict migrate_a migrate_b old =
    old
        |> AssocList.toList
        |> List.map (Tuple.mapBoth migrate_a migrate_b)
        |> AssocList.fromList


migrate_AssocSet_Set : (a_old -> a_new) -> AssocSet.Set a_old -> AssocSet.Set a_new
migrate_AssocSet_Set migrate_a old =
    old |> AssocSet.map migrate_a


migrate_DebugParser_ElmValue_ElmValue : Evergreen.V31.DebugParser.ElmValue.ElmValue -> Evergreen.V36.DebugParser.ElmValue.ElmValue
migrate_DebugParser_ElmValue_ElmValue old =
    case old of
        Evergreen.V31.DebugParser.ElmValue.Plain p0 ->
            Evergreen.V36.DebugParser.ElmValue.Plain (p0 |> migrate_DebugParser_ElmValue_PlainValue)

        Evergreen.V31.DebugParser.ElmValue.Expandable p0 ->
            Evergreen.V36.DebugParser.ElmValue.Expandable (p0 |> migrate_DebugParser_ElmValue_ExpandableValue)


migrate_DebugParser_ElmValue_ExpandableValue : Evergreen.V31.DebugParser.ElmValue.ExpandableValue -> Evergreen.V36.DebugParser.ElmValue.ExpandableValue
migrate_DebugParser_ElmValue_ExpandableValue old =
    case old of
        Evergreen.V31.DebugParser.ElmValue.ElmSequence p0 p1 ->
            Evergreen.V36.DebugParser.ElmValue.ElmSequence (p0 |> migrate_DebugParser_ElmValue_SequenceType)
                (p1 |> List.map migrate_DebugParser_ElmValue_ElmValue)

        Evergreen.V31.DebugParser.ElmValue.ElmType p0 p1 ->
            Evergreen.V36.DebugParser.ElmValue.ElmType p0
                (p1 |> List.map migrate_DebugParser_ElmValue_ElmValue)

        Evergreen.V31.DebugParser.ElmValue.ElmRecord p0 ->
            Evergreen.V36.DebugParser.ElmValue.ElmRecord (p0 |> List.map (Tuple.mapSecond migrate_DebugParser_ElmValue_ElmValue))

        Evergreen.V31.DebugParser.ElmValue.ElmDict p0 ->
            Evergreen.V36.DebugParser.ElmValue.ElmDict (p0 |> List.map (Tuple.mapBoth migrate_DebugParser_ElmValue_ElmValue migrate_DebugParser_ElmValue_ElmValue))


migrate_DebugParser_ElmValue_PlainValue : Evergreen.V31.DebugParser.ElmValue.PlainValue -> Evergreen.V36.DebugParser.ElmValue.PlainValue
migrate_DebugParser_ElmValue_PlainValue old =
    case old of
        Evergreen.V31.DebugParser.ElmValue.ElmString p0 ->
            Evergreen.V36.DebugParser.ElmValue.ElmString p0

        Evergreen.V31.DebugParser.ElmValue.ElmChar p0 ->
            Evergreen.V36.DebugParser.ElmValue.ElmChar p0

        Evergreen.V31.DebugParser.ElmValue.ElmNumber p0 ->
            Evergreen.V36.DebugParser.ElmValue.ElmNumber p0

        Evergreen.V31.DebugParser.ElmValue.ElmBool p0 ->
            Evergreen.V36.DebugParser.ElmValue.ElmBool p0

        Evergreen.V31.DebugParser.ElmValue.ElmFunction ->
            Evergreen.V36.DebugParser.ElmValue.ElmFunction

        Evergreen.V31.DebugParser.ElmValue.ElmInternals ->
            Evergreen.V36.DebugParser.ElmValue.ElmInternals

        Evergreen.V31.DebugParser.ElmValue.ElmUnit ->
            Evergreen.V36.DebugParser.ElmValue.ElmUnit

        Evergreen.V31.DebugParser.ElmValue.ElmFile p0 ->
            Evergreen.V36.DebugParser.ElmValue.ElmFile p0

        Evergreen.V31.DebugParser.ElmValue.ElmBytes p0 ->
            Evergreen.V36.DebugParser.ElmValue.ElmBytes p0


migrate_DebugParser_ElmValue_SequenceType : Evergreen.V31.DebugParser.ElmValue.SequenceType -> Evergreen.V36.DebugParser.ElmValue.SequenceType
migrate_DebugParser_ElmValue_SequenceType old =
    case old of
        Evergreen.V31.DebugParser.ElmValue.SeqSet ->
            Evergreen.V36.DebugParser.ElmValue.SeqSet

        Evergreen.V31.DebugParser.ElmValue.SeqList ->
            Evergreen.V36.DebugParser.ElmValue.SeqList

        Evergreen.V31.DebugParser.ElmValue.SeqArray ->
            Evergreen.V36.DebugParser.ElmValue.SeqArray

        Evergreen.V31.DebugParser.ElmValue.SeqTuple ->
            Evergreen.V36.DebugParser.ElmValue.SeqTuple


migrate_Types_BackendMsg : Evergreen.V31.Types.BackendMsg -> Evergreen.V36.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V31.Types.NoOpBackendMsg ->
            Evergreen.V36.Types.NoOpBackendMsg

        Evergreen.V31.Types.ClientDisconnected p0 p1 ->
            Evergreen.V36.Types.ClientDisconnected p0 p1

        Evergreen.V31.Types.GotTime p0 p1 p2 p3 ->
            Evergreen.V36.Types.GotTime p0 p1 (p2 |> migrate_Types_ToBackend) p3

        Evergreen.V31.Types.HourlyCheck p0 ->
            Evergreen.V36.Types.HourlyCheck p0

        Evergreen.V31.Types.GotTimeForDataEndpoint p0 p1 p2 ->
            Evergreen.V36.Types.GotTimeForDataEndpoint p0 (p1 |> migrate_Types_DataType) p2


migrate_Types_BackendMsgEvent_ : Evergreen.V31.Types.BackendMsgEvent_ -> Evergreen.V36.Types.BackendMsgEvent_
migrate_Types_BackendMsgEvent_ old =
    { msg = old.msg |> migrate_DebugParser_ElmValue_ElmValue
    , newModel = old.newModel |> migrate_DebugParser_ElmValue_ElmValue
    , cmd = old.cmd |> Maybe.map migrate_DebugParser_ElmValue_ElmValue
    , time = Time.millisToPosix 0
    }


migrate_Types_DataType : Evergreen.V31.Types.DataType -> Evergreen.V36.Types.DataType
migrate_Types_DataType old =
    case old of
        Evergreen.V31.Types.Init p0 ->
            Evergreen.V36.Types.Init (p0 |> migrate_Types_Init_)

        Evergreen.V31.Types.Update p0 ->
            Evergreen.V36.Types.Update (p0 |> migrate_Types_Update_)

        Evergreen.V31.Types.UpdateFromFrontend p0 ->
            Evergreen.V36.Types.UpdateFromFrontend (p0 |> migrate_Types_UpdateFromFrontend_)


migrate_Types_DebugSession : Evergreen.V31.Types.DebugSession -> Evergreen.V36.Types.DebugSession
migrate_Types_DebugSession old =
    { initialModel = old.initialModel |> Maybe.map migrate_DebugParser_ElmValue_ElmValue
    , initialCmd = old.initialCmd |> Maybe.map migrate_DebugParser_ElmValue_ElmValue
    , history = old.history |> Array.map migrate_Types_Event
    , connections = old.connections
    , settings = old.settings |> migrate_Types_DebugSessionSettings
    , lastChange = old.lastChange
    }


migrate_Types_DebugSessionSettings : Evergreen.V31.Types.DebugSessionSettings -> Evergreen.V36.Types.DebugSessionSettings
migrate_Types_DebugSessionSettings old =
    { filter = old.filter
    , collapsedFields = old.collapsedFields |> migrate_AssocSet_Set (List.map migrate_Types_PathNode)
    }


migrate_Types_Event : Evergreen.V31.Types.Event -> Evergreen.V36.Types.Event
migrate_Types_Event old =
    case old of
        Evergreen.V31.Types.BackendMsgEvent p0 ->
            Evergreen.V36.Types.BackendMsgEvent (p0 |> migrate_Types_BackendMsgEvent_)

        Evergreen.V31.Types.ToBackendEvent p0 ->
            Evergreen.V36.Types.ToBackendEvent (p0 |> migrate_Types_ToBackendEvent_)


migrate_Types_FrontendModel : Evergreen.V31.Types.FrontendModel -> Evergreen.V36.Types.FrontendModel
migrate_Types_FrontendModel old =
    case old of
        Evergreen.V31.Types.LoadingSession p0 ->
            Evergreen.V36.Types.LoadingSession (p0 |> migrate_Types_LoadingData)

        Evergreen.V31.Types.LoadedSession p0 ->
            Evergreen.V36.Types.LoadedSession (p0 |> migrate_Types_LoadedData)


migrate_Types_Init_ : Evergreen.V31.Types.Init_ -> Evergreen.V36.Types.Init_
migrate_Types_Init_ old =
    { sessionName = old.sessionName |> migrate_Types_SessionName
    , model = old.model |> migrate_DebugParser_ElmValue_ElmValue
    , maybeCmd = old.maybeCmd |> Maybe.map migrate_DebugParser_ElmValue_ElmValue
    , time = Time.millisToPosix 0 |> Just
    }


migrate_Types_LoadedData : Evergreen.V31.Types.LoadedData -> Evergreen.V36.Types.LoadedData
migrate_Types_LoadedData old =
    { key = old.key
    , sessionName = old.sessionName |> migrate_Types_SessionName
    , initialModel = old.initialModel |> Maybe.map migrate_DebugParser_ElmValue_ElmValue
    , initialCmd = old.initialCmd |> Maybe.map migrate_DebugParser_ElmValue_ElmValue
    , history = old.history |> Array.map migrate_Types_Event
    , selected = old.selected
    , indexOffset = old.indexOffset
    , settings = old.settings |> migrate_Types_DebugSessionSettings
    , debounceCounter = old.debounceCounter
    }


migrate_Types_LoadingData : Evergreen.V31.Types.LoadingData -> Evergreen.V36.Types.LoadingData
migrate_Types_LoadingData old =
    { key = old.key
    , sessionName = old.sessionName |> migrate_Types_SessionName
    }


migrate_Types_PathNode : Evergreen.V31.Types.PathNode -> Evergreen.V36.Types.PathNode
migrate_Types_PathNode old =
    case old of
        Evergreen.V31.Types.FieldNode p0 ->
            Evergreen.V36.Types.FieldNode p0

        Evergreen.V31.Types.VariantNode p0 ->
            Evergreen.V36.Types.VariantNode p0

        Evergreen.V31.Types.SequenceNode p0 ->
            Evergreen.V36.Types.SequenceNode p0

        Evergreen.V31.Types.DictNode p0 ->
            Evergreen.V36.Types.DictNode (p0 |> migrate_DebugParser_ElmValue_ElmValue)


migrate_Types_SessionName : Evergreen.V31.Types.SessionName -> Evergreen.V36.Types.SessionName
migrate_Types_SessionName old =
    case old of
        Evergreen.V31.Types.SessionName p0 ->
            Evergreen.V36.Types.SessionName p0


migrate_Types_ToBackend : Evergreen.V31.Types.ToBackend -> Evergreen.V36.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V31.Types.LoadSessionRequest p0 ->
            Evergreen.V36.Types.LoadSessionRequest (p0 |> migrate_Types_SessionName)

        Evergreen.V31.Types.ResetSessionRequest ->
            Evergreen.V36.Types.ResetSessionRequest

        Evergreen.V31.Types.SetSessionSettingsRequest p0 ->
            Evergreen.V36.Types.SetSessionSettingsRequest (p0 |> migrate_Types_DebugSessionSettings)


migrate_Types_ToBackendEvent_ : Evergreen.V31.Types.ToBackendEvent_ -> Evergreen.V36.Types.ToBackendEvent_
migrate_Types_ToBackendEvent_ old =
    { msg = old.msg |> migrate_DebugParser_ElmValue_ElmValue
    , newModel = old.newModel |> migrate_DebugParser_ElmValue_ElmValue
    , sessionId = old.sessionId
    , clientId = old.clientId
    , cmd = old.cmd |> Maybe.map migrate_DebugParser_ElmValue_ElmValue
    , time = Time.millisToPosix 0
    }


migrate_Types_ToFrontend : Evergreen.V31.Types.ToFrontend -> Evergreen.V36.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V31.Types.LoadSessionResponse p0 ->
            Evergreen.V36.Types.LoadSessionResponse (p0 |> migrate_Types_DebugSession)

        Evergreen.V31.Types.SessionUpdate p0 ->
            Evergreen.V36.Types.SessionUpdate
                (p0 |> migrate_Types_DataType)
                (Time.millisToPosix 0)

        Evergreen.V31.Types.ResetSession ->
            Evergreen.V36.Types.ResetSession


migrate_Types_UpdateFromFrontend_ : Evergreen.V31.Types.UpdateFromFrontend_ -> Evergreen.V36.Types.UpdateFromFrontend_
migrate_Types_UpdateFromFrontend_ old =
    { sessionName = old.sessionName |> migrate_Types_SessionName
    , msg = old.msg |> migrate_DebugParser_ElmValue_ElmValue
    , newModel = old.newModel |> migrate_DebugParser_ElmValue_ElmValue
    , sessionId = old.sessionId
    , clientId = old.clientId
    , maybeCmd = old.maybeCmd |> Maybe.map migrate_DebugParser_ElmValue_ElmValue
    , time = Time.millisToPosix 0 |> Just
    }


migrate_Types_Update_ : Evergreen.V31.Types.Update_ -> Evergreen.V36.Types.Update_
migrate_Types_Update_ old =
    { sessionName = old.sessionName |> migrate_Types_SessionName
    , msg = old.msg |> migrate_DebugParser_ElmValue_ElmValue
    , newModel = old.newModel |> migrate_DebugParser_ElmValue_ElmValue
    , maybeCmd = old.maybeCmd |> Maybe.map migrate_DebugParser_ElmValue_ElmValue
    , time = Time.millisToPosix 0 |> Just
    }
